"""add rating to books

Revision ID: 61ce7dbcf599
Revises: ada9d9f996c7
Create Date: 2026-06-14 00:38:07.351835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61ce7dbcf599'
down_revision: Union[str, Sequence[str], None] = 'ada9d9f996c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('rating', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'rating')
    # ### end Alembic commands ###
